version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "gitsubmodule"
    directory: "/program-analysis/medusa"
    schedule:
      interval: "daily" # Check for updates daily
    commit-message:
      prefix: "Update medusa"
    assignees:
      - ggrieco-tob
    reviewers:
      - ggrieco-tob
  - package-ecosystem: "gitsubmodule"
    directory: "/program-analysis/slither"
    schedule:
      interval: "daily" # Check for updates daily
    commit-message:
      prefix: "Update slither"
    assignees:
      - ggrieco-tob
    reviewers:
      - ggrieco-tob
