name: Run Slither tests

on:
  push:
    paths:
      - ".github/workflows/slither.yml"
      - "program-analysis/slither/**/*.py"
    branches:
      - master
  pull_request:
    paths:
      - ".github/workflows/slither.yml"
      - "program-analysis/slither/**/*.py"
  schedule:
    # run CI every day even if no PRs/merges occur
    - cron: "0 12 * * *"

jobs:
  tests:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          pip install solc-select
          solc-select install 0.5.11
          solc-select use 0.5.11
      - name: Run Tests
        run: |
          bash program-analysis/slither/scripts/gh_action_test.sh
